---
title: "portfolio-part-1"
format: html
---

## Describing data

1.  The first data set is from Cal Recycle and is the Multi-Year County Wide Origin Summary for Monterey. It is found at <https://www2.calrecycle.ca.gov/LGCentral/DisposalReporting/Origin/CountywideSummary> on Cal Recycle's website. This data is called `CountywideSummary.xlsx`

    The second data source (broken in to two tables) is from the US Census Bureau QuickFacts table. It contains some estimates from vintage year 2024 and 2025 other years date back to 2010. The Census data is from the 2010 Census of Population and Housing and the 2020 Census fo Population and Housing. Other data comes from a variety of sources. All data was accessed on March 22, 2026. It can be found at <https://www.census.gov/quickfacts/fact/table/pacificgrovecitycalifornia,montereycitycalifornia,marinacitycalifornia,kingcitynorthcarolina,greenfieldcitycalifornia,gonzalescitycalifornia/PST045224> and <https://www.census.gov/quickfacts/fact/table/soledadcitycalifornia,seasidecitycalifornia,salinascitycalifornia/PST045224>. This data is called `QuickFacts Mar-22-2026 (1).csv` and `QuickFacts Mar-22-2026.csv`

2.  The first data set, a county wide recycling summary for Monterey county contains the variables Report Year; Report Quarter, which lists each of the four quarters of the year and is broken down in to cities with in Monterey county; Disposal Ton, my guess as to what this means is the amount of waste produced within that jurisdiction within that time period; Export Ton; Transformation Ton; and Total ADC, ADC stands for alternate daily cover which is material other than soil used to cover a landfill.

    The Second data set contains a variety of infromation on people, businesses and geograph of cities over 5,000 people in Monterey County, CA. The variables are Fact, which contains the name of the fact listed; Fact Note; city name for each city, which contains the value for the respective fact; and Value Note for each city.
    
3. Question 1: How does population size of a city, for cities over 5000 people, affect waste generation per person in Monterey county?

    Question 2: How does population size per square mile affect waste generation per person for cities over 5000 people in Monterey County?

    Question 3: How has waste generation changed from 1995 in Monterey County?
